version: "2"
services:
  chatbot:
    image: kitunda/whatsapp-chatbot:latest
    ports:
      - 3001:3001
    environment:
      - JVM_OPTS=-Xmx128m -Xms128m
      - APPLICATION_VERIFICATION_TOKEN=
      - APPLICATION_APP_ID=
      - APPLICATION_APP_SECRET=
      - APPLICATION_PHONE_NUMBER_ID=
      - APPLICATION_BUSINESS_ACCOUNT_ID=
      - APPLICATION_ACCESS_TOKEN=
      - APPLICATION_VERSION=v15.0
      - APPLICATION_TEMPLATE_NAME_PREFIX=
      - APPLICATION_BASE_URL=https://graph.facebook.com/
      - "TZ=Africa/Nairobi"
    restart: on-failure
